#!/usr/bin/env python
__cvs_id__ = '$Id: setup,v 1.1 2005/01/25 03:14:59 dorionc Exp $'

import os
import plearn.utilities.ppath as ppath

## Syncronization with the environment variable
plearndir       = os.getenv( 'PLEARNDIR',     'HOME:PLearn'             )
libdir          = os.getenv( 'PLEARN_LIBDIR', 'PLEARNDIR:external_libs' )

## Adding the standard PLearn-wide bindings
ppath.add_binding('HOME',           "${HOME}" )
ppath.add_binding('PLEARNDIR',      plearndir )
ppath.add_binding('PLEARN_LIBDIR',  libdir    )

## This function writes the file down
ppath.write_bindings()
