#!/usr/bin/env python
__cvs_id__ = '$Id$'

import os
import plearn.utilities.ppath as ppath

## Synchronization with the environment variable
plearndir       = os.getenv( 'PLEARNDIR',     'HOME:PLearn'             )
dbdir           = os.getenv( 'DBDIR',         '/u/lisa/Database'        )

## Adding the standard PLearn-wide bindings
ppath.add_binding('HOME',           "${HOME}" )
ppath.add_binding('PLEARNDIR',      plearndir )
ppath.add_binding('PLEARN_LIBDIR',  "${PLEARN_LIBDIR}" )
ppath.add_binding('DBDIR',          dbdir )
ppath.add_binding('UCI_MLDB_REP',   "DBDIR:UCI_MLDB" )
ppath.add_binding('UCI_MLDB',       "PLEARNDIR:examples/data/uci_mldb"  )

## This function writes the file down
ppath.write_bindings()

