#!/usr/bin/env python
__cvs_id__ = '$Id$'

import os
import plearn.utilities.ppath as ppath

## Synchronization with the environment variable
plearndir       = os.getenv( 'PLEARNDIR',     'HOME:PLearn'             )
libdir          = os.getenv( 'PLEARN_LIBDIR', 'PLEARNDIR:external_libs' )

## Adding the standard PLearn-wide bindings
ppath.add_binding('HOME',           "${HOME}" )
ppath.add_binding('PLEARNDIR',      plearndir )
ppath.add_binding('PLEARN_LIBDIR',  "${PLEARN_LIBDIR}" )
ppath.add_binding('UCI_MLDB',       "PLEARNDIR:examples/data/uci_mldb"  )

## This function writes the file down
ppath.write_bindings()

