#! /bin/sh
# Will append the statistics of an experiment to an ascii file (typically a .amat file).
# *** It needs 'plearn_full' to be compiled and in the path ***
# Typical usage is to put in the final_commands option of a PTester:
#   appendresults ${dir} results.amat ${param_1} ${param_2} ... ${param_n}

if [ "$3" = "" ]; then
  echo Usage: $0 dir output param_1 ... param_n
  echo See code for more info.
  exit 127
fi
DIR="$1"
OUTPUT="$2"
shift
shift
PARAMS="$1 "
shift
for PARAM in $@; do
PARAMS="$PARAMS""$PARAM "
done

# Wait until nobody else is messing with the output file.
lockfile $OUTPUT.lock

echo -n "$PARAMS" >> $OUTPUT
plearn_full vmat cat $DIR/global_stats.pmat "rowindex 1 ==" >> $OUTPUT

# Release the lock
rm -f $OUTPUT.lock

