#! /bin/sh
# Will append the statistics of an experiment to an ascii file (typically a .amat file).
# *** It needs 'plearn' to be compiled and in the path ***
# Typical usage is to put in the final_commands option of a PTester:
#   appendresults ${dir} results.amat ${param_1} ${param_2} ... ${param_n}

if [ "$3" = "" ]; then
  echo "Usage:"
  echo "     $0 dir output param_1 ... param_n"
  echo "OR   $0 output param_1 ... param_n perf_1 ... perf_m"
  echo "See code for more info."
  exit 127
fi
DIR="$1"
shift
if [ -d $DIR ];then
    OUTPUT="$1"
    shift
else
    OUTPUT=$DIR
fi
if [ ! -f $OUTPUT ];then
    echo "$OUTPUT is not a file!"
    exit 69
fi

PARAMS="$1 "
shift
for PARAM in $@; do
PARAMS="$PARAMS""$PARAM "
done

# Wait until nobody else is messing with the output file.
# We wait 60s in case the filesystem is too busy.
# In that case retrying too often would make it worse.
lockfile -60 $OUTPUT.lock

if [ -d $DIR ];then
    echo -n "$PARAMS" >> $OUTPUT
    plearn vmat cat $DIR/global_stats.pmat "rowindex 1 ==" >> $OUTPUT
else
    echo "$PARAMS" >> $OUTPUT
fi

# Release the lock
rm -f $OUTPUT.lock

