#!/usr/bin/env python
#
# cldispatch: dispatch utility for parallel PLearn
#
# Copyright 2004, Apstat Technologies, inc.
# All rights reserved.

from optparse import OptionParser
from plearn.parallel.dispatch import *

#
# Main
#

def main():
    parser = OptionParser()
    parser.add_option('-n', '--num-available-machines',
                      help='Prints the number of available machines',
                      action='store_true', default=False)
    
    (options, args) = parser.parse_args()


    if options.num_available_machines:
        print Task.availableMachinesCount()
    elif args:        
        launch_task( args, wait = True )

if __name__ == '__main__':
    main()
