#!/usr/bin/env python

# csv_convert
# Copyright (C) 2007 Christian Dorion
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. The name of the authors may not be used to endorse or promote
#      products derived from this software without specific prior written
#      permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
#  NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  This file is part of the PLearn library. For more information on the PLearn
#  library, go to the PLearn Web site at www.plearn.org
"""Usage: csv_convert [TARGETS]

TARGETS can be single dot-{a,p}mat files or directories. For single files,
this script is equivalent to calling 'plearn FILE.pmat CSV/FILE.csv'. For
directories, a loop performs the conversion on all dot-{a,p}mat files in
the directories. If no targets are provided, the current working directory
is the default target. Example:

    csv_convert File.pmat Subdir1/ Subdir2/Single.amat

All CSV files are created in a CSV directory under the current working
directory.
"""
import os, sys
targets = sys.argv[1:]
if not targets:
    targets = [ os.getcwd() ]

help = False
if "-h" in targets:
    targets.remove("-h")
    help = True
elif "--help" in targets:
    targets.remove("--help")
    help = True

if help:
    print __doc__
    sys.exit(0)

for target in targets:
    if os.path.isdir(target):
        dirlist = os.listdir(target)
    else:
        target, fname = os.path.split(target)
        dirlist = [ fname ]

    for fname in dirlist:
        froot, ext = os.path.splitext(fname)
        if ext in [ ".amat", ".pmat" ]:
            if not os.path.exists("CSV"):
                os.mkdir("CSV")
            print "Converting", os.path.join(target,fname)
            os.system("plearn --no-version --no-progress vmat convert "
                "%s CSV/%s.csv --convert-date"%( os.path.join(target,fname), froot ))
