#!/bin/bash
#Script that compile a target multiple time with different compilation option
#To differenciate the different target we create hardlink to the original file
#Exemple: multipymake plearn -float -double
#         This will create the hard link: plearn-float.cc and plearn-double.cc
#         This will execute pymake -float -link plearn-float.cc and
#                           pymake -double -link plearn-double.cc
#Exemple2: multipymake plearn "-float -opt" "-double -opt"
#!!Do not work, must remove space from name
#         This will create the hard link: plearn-float.cc and plearn-double.cc
#         This will execute pymake -float -opt -link plearn-float.cc and
#                           pymake -double -opt -link plearn-double.cc

if [ $# -ge 3 ]; then
    BASEPROG=$1
    shift
else
    echo "Usage: $0 <base_prog> <List of parameter> ..."
 fi
ALL=" -link "

for i in "$@";
  do
  iname=${i//\ /_}
  ln ${BASEPROG}.cc ${BASEPROG}${iname}.cc
done

for i in "$@";
  do
  iname=${i//\ /_}
  echo -n "Compiling ${BASEPROG}${i}.cc..."
  pymake $i $ALL ${BASEPROG}${iname}.cc &>/dev/null|| ( echo "Build failed for $i"; exit)
  echo "Ended with status: $?"
done
