#!/usr/bin/env python

# pldiff
# Copyright (C) 2006 Christian Dorion
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. The name of the authors may not be used to endorse or promote
#      products derived from this software without specific prior written
#      permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
#  NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  This file is part of the PLearn library. For more information on the PLearn
#  library, go to the PLearn Web site at www.plearn.org
"""PLDiff is a script meant to compare PLearn-stuffed directories recursively.

Usage: pldiff <former> <later> [--option_i=option_value_i]*

Both <former> and <later> must be files or valid directories which would be be
compared recursively. Recursively-empty directories and links will be
neglected.

Type 'pldiff -h' for help on options.
"""
import sys
from optparse import OptionParser
from plearn.utilities import pldiff

parser = OptionParser( usage = __doc__ )

parser.add_option( '-p', '--precision',
                   default = "1e-06",                   
                   help = "Tolerance for float numbers' comparison" )

parser.add_option( '--plearn-exec',
                   default = "plearn_tests",                   
                   help = "By default, PLearn's vmats and serialization files are compared using "
                   "'plearn_tests'. If provided, the --plearn-exec option value will be understood "
                   "to be the plearn-compliant executable to use in place of 'plearn_tests'. Make "
                   "sure your program is compiled and accepts --no-version and --verbosity arguments"
                   "(they will if built over plearn_main.cc)" )

parser.add_option( '--psave-resources',
                   default = "",                   
                   help = "CSV list of the local results that may be used by any psaved experiment." )

options, targets = parser.parse_args()

if len(targets) != 2:
    print __doc__
    sys.exit()
    
pldiff.set_plearn_exec(options.plearn_exec)
diff_result = pldiff.pldiff(targets[0], targets[1], float(options.precision))

if diff_result:
    print
    for d in diff_result:
        print d
    
