#!/usr/bin/python
# Martin Monperrus
# get the free machines from a file

## commande pour avoir les reservations
res_cmd = 'cat /u/clacutl/reserv/data'

import re;
import sys;
import os;


# lecture des donnees du cluster
# sans utiliser la conmande cluster car
# elle n'est pas robuste

f = os.popen(res_cmd);
l = f.readlines();
res = '';
f.close();
for x in l[:]:
	res = res+x;

#print s;

# lecture des machines possibles
f=open(sys.argv[1], 'r');
fr=open(sys.argv[2], 'w');

l = f.readlines();

#print l;

for x in l[:]:

	comment = re.findall('#', x);  #si c'est une ligne commentee
	
	if len(x)>1 and len(comment)==0:
		s = re.findall('.*\.i', x); # recuperation juste de l'id
		mach = s[0][:-2];	
		s2 = re.findall(mach,res);
	# 	print s2;

		if len(s2) == 0: # si la machine n'est pas dans les reservations du cluster
			print >>fr, mach
            #print mach;
	

f.close();
fr.close();