#!/usr/bin/python
# Martin Monperrus
# get the free machines

import re;
import sys;
import os;
import string

if len(sys.argv)<2:
	print 'Usage: pyfreemachines [output_file]'
	sys.exit()

# lecture des machines du cluster du LISA
res_file = '/u/clacutl/libexec/libclac.pl'
f = open(res_file);
l = f.readlines();
f.close();
res = string.join(l,'');
machines_lisa= re.findall('([a-z]{4}\d{2}) => { panne => 0, groupe => \'lisa\'.*', res);


# lecture des machines reservees
res_file = '/u/clacutl/reserv/data'
f = open(res_file);
machines_reservees = string.join(f.readlines(),'\n');
f.close();

# ouverture du fichier de resultat
f=open(sys.argv[1], 'w');


for x in machines_lisa[:]:
	s2 = re.findall(x,machines_reservees);
	if len(s2) == 0: # si la machine n'est pas dans les reservations du cluster
		print >>f, x

# fermeture du fichier
f.close();
