#!/usr/bin/python
# Martin Monperrus
# modified by
# Jasmin Lapalme (01/2005)
# get the free machines on the cluster depending on the type of cpu (64 or 32 bits)

import re;
import sys;
import os;
import string

if len(sys.argv)<2:
	print 'Usage: pyfreemachines [output_file]'
	sys.exit()

# lecture des machines du cluster du LISA
res_file = '/u/clacutl/libexec/libclac.pl'
f = open(res_file);
l = f.readlines();
f.close();
res = string.join(l,'');

linux_type = os.uname()[4]
if linux_type != 'x86_64':
	machines_lisa= re.findall('([a-z]{4}\d{2}) => { panne => 0, groupe => \'lisa\'.*', res);
else:
	machines_lisa= re.findall('([a-z]{4}\d{2}) => { panne => 0, groupe => \'clop\'.*type_cpu => \'x86_64\'.*', res);


# lecture des machines reservees
res_file = '/u/clacutl/reserv/data'
f = open(res_file);
machines_reservees = string.join(f.readlines(),'\n');
f.close();

# ouverture du fichier de resultat
f=open(sys.argv[1], 'w');


for x in machines_lisa[:]:
	s2 = re.findall(x,machines_reservees);
	if len(s2) == 0: # si la machine n'est pas dans les reservations du cluster
		print >>f, x

# fermeture du fichier
f.close();
