#!/bin/bash

# Sets up a PLearn build environment, then runs the command supplied on the
# command-line inside that environment.

if [ ! -f plearn/base/PP.h ]; then
    echo "The directory '`pwd`' does not look like a Plearn checkout home dir. Bailing out."
    exit 150
fi

PLEARNDIR="`pwd`"
PLEARN_LIBDIR="$PLEARNDIR/external_libs"

PATH="$PLEARNDIR/scripts:$PLEARNDIR/commands:$PATH"
PYTHONPATH="$PLEARNDIR/python_modules"

export PLEARNDIR
export PLEARN_LIBDIR
export PATH
export PYTHONPATH

exec "$@"
