#!/bin/bash

# Sets up a PLearn build/test environment, then runs the command supplied on the
# command-line inside that environment.

if [ ! -f plearn/base/PP.h ]; then
    echo "The directory '`pwd`' does not look like a Plearn checkout home dir. Bailing out."
    exit 150
fi

# Set up ppaths needed by compilation and tests.
export PLEARNDIR="`pwd`"
export PLEARN_LIBDIR="$PLEARNDIR/external_libs"

# Set up path for shell and python
export PATH="$PLEARNDIR/scripts:$PLEARNDIR/commands:/usr/local/bin:$PATH"
export PYTHONPATH="$PLEARNDIR/python_modules"

exec "$@"
