#!/bin/sh
# superkill, a dangerous but useful kill command
# Copyright (C) 2003 Pascal Vincent
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. The name of the authors may not be used to endorse or promote
#      products derived from this software without specific prior written
#      permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
#  NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ $# -eq 0 ]; then 
   echo "Usage: superkill pattern [kill options]"
   echo "Will fetch all processes in the ps listing"
   echo "that match the given grep pattern and show them."
   echo "It will ask confirmation *once* to kill the whole batch"
   echo "kill options are passed to the kill command (ex: -9)"
   echo "Ex: superkill '\bps\b' -9"
   exit
else
  pattern=$1
  shift
  echo ------------------------------------
  ps aux --cols=1000 | grep -e $pattern | grep -v -e '\bsuperkill\b' | grep -v -e '\bgrep\b'
  echo ------------------------------------
  echo -n "ARE YOU SURE YOU WANT TO kill $* THEM ALL (y/n)? "
  read answer;
  if [ "$answer" != "" ] && [ "$answer" = "y" ] || [ "$answer" = "yes" ] || [ "$answer" = "Y" ] || [ "$answer" = "YES" ]; then 
    ps aux --cols=1000 | grep -e $pattern | grep -v -e '\bsuperkill\b' | grep -v -e '\bgrep\b' | awk '{ print $2 }' | xargs kill $*
    echo "Done."
  else 
    echo "Aborted!";
  fi
fi
