#!/usr/bin/env python

# toldiff
# Copyright (C) 2005 Pascal Vincent
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. The name of the authors may not be used to endorse or promote
#      products derived from this software without specific prior written
#      permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
#  NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  This file is part of the PLearn library. For more information on the PLearn
#  library, go to the PLearn Web site at www.plearn.org

"""
Usage: toldiff <file1> <file2> [<numeric_tolerance>] [<whitespace_tolerance>]

toldiff compares two files while being tolerant to small relative
differences between ascii numbers.

If the two files are considered the same, the script outputs nothing.
If there are noticeable differences, the script will output the
character positions before which they appear to differ.

numeric_tolerance (tol) is 1e-6 by default.

If min(|a|,|b|)<1 we use the absolute difference,
i.e. a and b are considered to differ if |a-b| > tol.

Otherwise, we use relative difference, i.e. a and b are
considered to differ if |a-b|/min(|a|,|b|) > tol.

whitespace_tolerance is 0 by default

If whitespace_tolerance is >0 then sequences of blanks (i.e. space, tab,
newline, carriage return) are considered equivalent if their lengths do
not differ by more than whitespace_tolerance characters.
"""

import sys

from plearn.utilities.pldiff import toldiff

args = sys.argv[1:] # ignore program name
if len(args)<2:
    print __doc__
    sys.exit()

filename1 = args[0]
filename2 = args[1]
try:
    numtol = float(args[2])
except IndexError:
    numtol = 1e-6
try:
    blanktol = int(args[3])
except IndexError:
    blanktol = 0

err = toldiff(filename1, filename2, numtol, blanktol)
if err:
    print err
    # Uncomment these lines if you want a more helpful output when toldiff fails.
    # import os
    # print 'Output of a standard diff command is:'
    # os.system('diff -u %s %s' % (filename1, filename2))
        
