#!/usr/bin/env python

# Copyright (C) 2001 Pascal Vincent
#/u/bengioy/PLearn/scripts/pymake
#  Redistribution and use in source and binary forms, with or without/u/bengioy/PLearn/scripts/pymake
#  modification, are permitted provided that the following conditions are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#   3. The name of the authors may not be used to endorse or promote
#      products derived from this software without specific prior written
#      permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
#  NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  This file is part of the PLearn library. For more information on the PLearn
#  library, go to the PLearn Web site at www.plearn.org

import sys, string, os

args = sys.argv[:]

helpstring =  """Usage:\n
    vmat_select_from_sources destdir "['condition1','condition2' ...]" "['name1','name2' ...]" source1 source2 ...\n
    This program creates as many vmat files for each source file as there are conditions. Each of them has the form\n
         <SOURCES>
           $i-th-source
         </SOURCES>
         <PREFILTER>
           $j-th-condition
         </PREFILTER>
         <PRECOMPUTE>dmat</PRECOMPUTE>\n
    and these files will be named destdir/<basename-of-i-th-source>_<name-j>.vmat. There must be as many
    names as there are conditions in these lists, obviously. Note that the condition and name lists
    must be comma-separated. Note also that the lists and their contents should be quoted (as
    in the example).
    """

if len(args)<5:
    print helpstring
    sys.exit()

destdir = args[1]
conditions = eval(args[2])
names = eval(args[3])
sources = args[4:]
ncond = len(conditions)
if ncond !=len(names):
    print "The number of conditions should be equal to the number of names.\n"
    print helpstring
    sys.exit()

for source in sources:
    for i in range(0,ncond):
        sname = os.path.basename(source)
        p = string.find(sname,'.')
        if p>=0:
            sname = sname[0:p]
        filename = destdir + "/" + sname + "_" + names[i] + ".vmat"
        f = open(filename,"w")
        f.write("<SOURCES>\n" + source + "\n</SOURCES>\n<PREFILTER>\n" + conditions[i] + "\n</PREFILTER>\n<PRECOMPUTE>dmat</PRECOMPUTE>\n")
        f.close()



