#!/usr/bin/env python2.3
import getopt, new, os, sys
from plearn.xperiments.Xperiment import *

def listdir( targets, options, xperiments ):
    print "\n","\n".join([ str(x) for x in xperiments ])

def mkdir( targets, options, xperiments ):    
    for exp in xperiments:
        if exp.infos:
            if options.name is None:
                dirname = "_".join([ "%s=%s" % (lhs, str(rhs))
                                     for (lhs, rhs) in exp.infos.iteritems() ])
            else:
                dirname = options.name

            if not os.path.exists( dirname ):
                os.mkdir( dirname )                
            os.system("(cd %s; ln -s ../%s)" % (dirname, exp.path))

def running( targets, options, xperiments ):
    assert not targets
    for exp in experiments:
        if not exp.infos:
            print exp
            
    
### Main program
mode    = listdir
targets = sys.argv[1:]
if targets:    
    if targets[0] == "listdir":    
        mode = listdir
        del targets[0]
        
    elif targets[0] == "mkdir":    
        mode = mkdir
        del targets[0]
        
    elif targets[0] == "running":    
        mode = running
        del targets[0]        

class __options: pass
options = new.instance( __options, {"name" : None } )

if "--name" in targets:
    index = targets.index("--name")
    del targets[index]
    
    options.name = targets[index]
    del targets[index]

### Starting the selected mode
experiments = Xperiment.load_experiments( targets )
mode( targets, options, experiments )
