#!/usr/bin/env python

import os
from plearn           import xperiments
from plearn.utilities import toolkit

# Builds are tuples of the form (major, minor, plearn_revision) where
# plearn_revision is the SVN revision of the PLearn project when the
# project's version was released.
build_list = [
    # Major, Minor, PLearn Rev 
    (   0,     1,       3646  )
    ]

def xpdir_version( ):
    xperiments_dir = os.path.dirname( xperiments.__file__ )
    vtup = toolkit.version( xperiments_dir, build_list )
    return '.'.join([ str(v) for v in vtup ])

xperiments.main( xpdir_version )
